/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.hibswingapp.ui;

import com.vektorel.hibswingapp.entity.Bolum;
import com.vektorel.hibswingapp.entity.Il;
import com.vektorel.hibswingapp.entity.Kullanici;
import com.vektorel.hibswingapp.service.BolumService;
import com.vektorel.hibswingapp.service.IlService;
import com.vektorel.hibswingapp.service.KullaniciService;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author soner
 */
public class frmAnasayfa extends javax.swing.JFrame {

    Kullanici kullanici;
    KullaniciService kullaniciService = new KullaniciService();
    BolumService bolumService = new BolumService();
    IlService ilService = new IlService();

    /**
     * Creates new form frmAnasayfa
     */
    public frmAnasayfa(Kullanici kullanici) {
        initComponents();
        this.kullanici = kullanici;
        setLocationRelativeTo(null);
        kullaniciTabloyuDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnasayfa = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuKullaniciListesi = new javax.swing.JMenuItem();
        mnuKullaniciEkle = new javax.swing.JMenuItem();
        mnuKullaniciSil = new javax.swing.JMenuItem();
        mnuKullaniciGuncelle = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuBolum = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        mnuBolumEkle = new javax.swing.JMenuItem();
        mnuBolumListele = new javax.swing.JMenuItem();
        mnuIlEkle = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAnasayfa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAnasayfa);

        jMenu1.setText("Kullanıcı İşlemleri");

        mnuKullaniciListesi.setText("Kullanıcı Listesi");
        mnuKullaniciListesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKullaniciListesiActionPerformed(evt);
            }
        });
        jMenu1.add(mnuKullaniciListesi);

        mnuKullaniciEkle.setText("Kullanıcı Ekle");
        mnuKullaniciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKullaniciEkleActionPerformed(evt);
            }
        });
        jMenu1.add(mnuKullaniciEkle);

        mnuKullaniciSil.setText("Kullanıcı Sil");
        mnuKullaniciSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKullaniciSilActionPerformed(evt);
            }
        });
        jMenu1.add(mnuKullaniciSil);

        mnuKullaniciGuncelle.setText("Kullanıcı Güncelle");
        mnuKullaniciGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKullaniciGuncelleActionPerformed(evt);
            }
        });
        jMenu1.add(mnuKullaniciGuncelle);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Öğrenci İşlemleri");
        jMenuBar1.add(jMenu2);

        mnuBolum.setText("Tanımlar");

        jMenu4.setText("Bölüm");

        mnuBolumEkle.setText("Bölüm Tanımla");
        mnuBolumEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBolumEkleActionPerformed(evt);
            }
        });
        jMenu4.add(mnuBolumEkle);

        mnuBolumListele.setText("Bölüm Listesi");
        mnuBolumListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBolumListeleActionPerformed(evt);
            }
        });
        jMenu4.add(mnuBolumListele);

        mnuBolum.add(jMenu4);

        mnuIlEkle.setText("İl Tanımla");
        mnuIlEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIlEkleActionPerformed(evt);
            }
        });
        mnuBolum.add(mnuIlEkle);

        jMenuBar1.add(mnuBolum);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuKullaniciListesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKullaniciListesiActionPerformed
        kullaniciTabloyuDoldur();
    }//GEN-LAST:event_mnuKullaniciListesiActionPerformed

    private void mnuKullaniciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKullaniciEkleActionPerformed
        frmKullaniciEkle ekle = new frmKullaniciEkle(this, true);
        ekle.show();
        kullaniciTabloyuDoldur();
    }//GEN-LAST:event_mnuKullaniciEkleActionPerformed

    private void mnuKullaniciSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKullaniciSilActionPerformed
        int seciliKayit = tblAnasayfa.getSelectedRow();
        if (seciliKayit > -1) {
            int silisinMi = (JOptionPane.showConfirmDialog(rootPane, "Silmek İstediğinize Emin misiniz?"));
            if (silisinMi == 0) {
                String value = tblAnasayfa.getValueAt(seciliKayit, 0).toString();
                Kullanici kullanici = kullaniciService.getById(new Long(value));
                kullaniciService.delete(kullanici);
                kullaniciTabloyuDoldur();
            }
        }
    }//GEN-LAST:event_mnuKullaniciSilActionPerformed

    private void mnuKullaniciGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKullaniciGuncelleActionPerformed
        int seciliKayit = tblAnasayfa.getSelectedRow();
        if (seciliKayit > -1) {
            String value = tblAnasayfa.getValueAt(seciliKayit, 0).toString();
            Kullanici k = kullaniciService.getById(new Long(value));
            frmKullaniciEkle guncelle = new frmKullaniciEkle(this, true, k);
            guncelle.show();
            kullaniciTabloyuDoldur();
        }
    }//GEN-LAST:event_mnuKullaniciGuncelleActionPerformed

    private void mnuBolumEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBolumEkleActionPerformed

        frmBolumEkle bolumEkle = new frmBolumEkle(this, true);
        bolumEkle.show();
        bolumTabloyuDoldur();
    }//GEN-LAST:event_mnuBolumEkleActionPerformed

    private void mnuBolumListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBolumListeleActionPerformed
        bolumTabloyuDoldur();
    }//GEN-LAST:event_mnuBolumListeleActionPerformed

    private void mnuIlEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIlEkleActionPerformed
        frmIlEkle ilEkle = new frmIlEkle(this, true);
        ilEkle.show();
        IlTabloyuDoldur();
    }//GEN-LAST:event_mnuIlEkleActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mnuBolum;
    private javax.swing.JMenuItem mnuBolumEkle;
    private javax.swing.JMenuItem mnuBolumListele;
    private javax.swing.JMenuItem mnuIlEkle;
    private javax.swing.JMenuItem mnuKullaniciEkle;
    private javax.swing.JMenuItem mnuKullaniciGuncelle;
    private javax.swing.JMenuItem mnuKullaniciListesi;
    private javax.swing.JMenuItem mnuKullaniciSil;
    private javax.swing.JTable tblAnasayfa;
    // End of variables declaration//GEN-END:variables

    private void kullaniciTabloyuDoldur() {
        List<Kullanici> kullanici = kullaniciService.getAll(null);
        String[][] data = new String[kullanici.size()][6];
        for (int i = 0; i < kullanici.size(); i++) {
            data[i][0] = kullanici.get(i).getId().toString();
            data[i][1] = kullanici.get(i).getAdSoyad();
            data[i][2] = kullanici.get(i).getUsername();

        }

        tblAnasayfa.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Id", "Ad Soyad", "Kullanıcı Adı"
                }
        ));
    }

    private void bolumTabloyuDoldur() {
        List<Bolum> bolum = bolumService.getAll(null);
        String[][] data = new String[bolum.size()][6];
        for (int i = 0; i < bolum.size(); i++) {
            data[i][0] = bolum.get(i).getId().toString();
            data[i][1] = bolum.get(i).getKod();
            data[i][2] = bolum.get(i).getBolumAdi();

        }

        tblAnasayfa.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Id", "Bolum Kodu", "Bolum Adı"
                }
        ));
    }

    private void IlTabloyuDoldur() {
        List<Il> il = ilService.getAll(null);
        String[][] data = new String[il.size()][6];
        for (int i = 0; i < il.size(); i++) {
            data[i][0] = il.get(i).getId().toString();
            data[i][1] = il.get(i).getKodu();
            data[i][2] = il.get(i).getAdi();

        }

        tblAnasayfa.setModel(new javax.swing.table.DefaultTableModel(
                data,
                new String[]{
                    "Id", "İl Kodu", "İl Adı"
                }
        ));
    }

}
