/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.hibswingapp.ui;

import com.vektorel.hibswingapp.entity.Bolum;
import com.vektorel.hibswingapp.service.BolumService;
import javax.swing.JOptionPane;

/**
 *
 * @author soner
 */
public class frmBolumEkle extends javax.swing.JDialog {

    /**
     * Creates new form frmBolumEkle
     */
    public frmBolumEkle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    frmBolumEkle() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBolumKodu = new javax.swing.JLabel();
        txtBolumKodu = new javax.swing.JTextField();
        lblBolumAdi = new javax.swing.JLabel();
        txtBolumAdi = new javax.swing.JTextField();
        btnBolumIptal = new javax.swing.JButton();
        btnBolumKaydet = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblBolumKodu.setText("Bölüm Kodu");

        lblBolumAdi.setText("Bölüm Adı");

        btnBolumIptal.setText("İptal");
        btnBolumIptal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolumIptalActionPerformed(evt);
            }
        });

        btnBolumKaydet.setText("Kaydet");
        btnBolumKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolumKaydetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBolumKodu)
                            .addComponent(lblBolumAdi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBolumKodu)
                            .addComponent(txtBolumAdi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnBolumIptal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBolumKaydet)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBolumKodu)
                    .addComponent(txtBolumKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBolumAdi)
                    .addComponent(txtBolumAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBolumIptal)
                    .addComponent(btnBolumKaydet))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBolumIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolumIptalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBolumIptalActionPerformed

    private void btnBolumKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolumKaydetActionPerformed
        try {
            BolumService bolumService = new BolumService();
            Bolum bolum = new Bolum();
            bolum.setKod(txtBolumKodu.getText());
            bolum.setBolumAdi(txtBolumAdi.getText());
            bolumService.save(bolum);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnBolumKaydetActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBolumIptal;
    private javax.swing.JButton btnBolumKaydet;
    private javax.swing.JLabel lblBolumAdi;
    private javax.swing.JLabel lblBolumKodu;
    private javax.swing.JTextField txtBolumAdi;
    private javax.swing.JTextField txtBolumKodu;
    // End of variables declaration//GEN-END:variables
}
